# Generated by Django 5.2.7 on 2025-11-25 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carga", "0002_alter_carga_criado_em_alter_carga_valor_total_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recebimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_recebimento", models.DateTimeField(auto_now_add=True)),
                (
                    "peso_conferido_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Peso em Kg conferido no momento do recebimento para checagem.",
                        max_digits=10,
                    ),
                ),
                (
                    "carga",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recebimento",
                        to="carga.carga",
                    ),
                ),
                (
                    "receptor",
                    models.ForeignKey(
                        limit_choices_to={"tipo_usuario": "RECEPTOR"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
