# Generated by Django 5.2.7 on 2025-11-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Residuo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PLASTICO", "Plástico"),
                            ("PAPEL", "Papel"),
                            ("VIDRO", "Vidro"),
                            ("METAL", "Metal"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Resíduo",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor monetário do resíduo, se aplicável.",
                        max_digits=10,
                        verbose_name="Valor (R$)",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
            ],
        ),
    ]
