# Generated by Django 5.2.7 on 2025-11-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("residuos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="residuo",
            options={"ordering": ["-data_criacao"]},
        ),
    ]
