# Generated by Django 5.2.7 on 2025-10-23 04:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("PRODUTOR", "Produtor"),
                            ("COLETOR", "Coletor"),
                            ("RECEPTOR", "Receptor"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Usuário",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Sobrenome"),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="Formato: 000.000.000-00", max_length=14, unique=True
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Formato: (00) 00000-0000", max_length=15
                    ),
                ),
                (
                    "endereco_completo",
                    models.CharField(max_length=255, verbose_name="Endereço Completo"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Coletor",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="perfil_coletor",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_veiculo",
                    models.CharField(max_length=50, verbose_name="Tipo de Veículo"),
                ),
                (
                    "capacidade_carga",
                    models.DecimalField(
                        decimal_places=2, help_text="Capacidade em kg", max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produtor",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="perfil_produtor",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receptor",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="perfil_receptor",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nome_empresa",
                    models.CharField(max_length=255, verbose_name="Nome da Empresa"),
                ),
                (
                    "cnpj",
                    models.CharField(
                        help_text="Formato: 00.000.000/0000-00",
                        max_length=18,
                        unique=True,
                    ),
                ),
                (
                    "endereco_comercial",
                    models.CharField(max_length=255, verbose_name="Endereço Comercial"),
                ),
                (
                    "horario_funcionamento",
                    models.CharField(
                        max_length=100, verbose_name="Horário de Funcionamento"
                    ),
                ),
                (
                    "tipos_de_residuo_aceitos",
                    models.CharField(
                        help_text="Ex: Plástico, Vidro, Metal", max_length=255
                    ),
                ),
            ],
        ),
    ]
