# Generated by Django 5.2.7 on 2025-11-16 03:12

import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receptor",
            name="cnpj",
            field=models.CharField(
                help_text="Pode ser informado com ou sem pontuação.",
                max_length=18,
                unique=True,
                validators=[usuarios.validators.validate_cnpj],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(
                help_text="Pode ser informado com ou sem pontuação.",
                max_length=14,
                unique=True,
                validators=[usuarios.validators.validate_cpf],
            ),
        ),
    ]
