# Generated by Django 5.2.7 on 2025-11-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_receptor_cnpj_alter_usuario_cpf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coletor",
            options={"ordering": ["usuario__username"]},
        ),
        migrations.AlterModelOptions(
            name="produtor",
            options={"ordering": ["usuario__username"]},
        ),
        migrations.AlterModelOptions(
            name="receptor",
            options={"ordering": ["nome_empresa"]},
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={"ordering": ["id"]},
        ),
    ]
