# Generated by Django 5.2.7 on 2025-11-25 06:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residuos", "0002_alter_residuo_options"),
        ("usuarios", "0003_alter_coletor_options_alter_produtor_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receptor",
            name="tipos_de_residuo_aceitos",
        ),
        migrations.CreateModel(
            name="ResiduoAceito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_minima",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("preco_unidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[("KG", "Kg"), ("UN", "Unidade")], max_length=10
                    ),
                ),
                (
                    "receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residuos_aceitos",
                        to="usuarios.receptor",
                    ),
                ),
                (
                    "residuo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="residuos.residuo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resíduo Aceito",
                "verbose_name_plural": "Resíduos Aceitos",
                "unique_together": {("receptor", "residuo")},
            },
        ),
        migrations.AddField(
            model_name="receptor",
            name="tipos_de_residuo_aceitos",
            field=models.ManyToManyField(
                blank=True,
                related_name="receptores",
                through="usuarios.ResiduoAceito",
                to="residuos.residuo",
            ),
        ),
    ]
