# Generated by Django 5.2.7 on 2025-11-16 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residuos", "0002_alter_residuo_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EM_COLETA", "Em Coleta"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                        verbose_name="Status da Carga",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "entregue_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Entrega"
                    ),
                ),
                (
                    "produtor",
                    models.ForeignKey(
                        limit_choices_to={"tipo_usuario": "PRODUTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargas_produzidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Produtor",
                    ),
                ),
                (
                    "residuos",
                    models.ManyToManyField(
                        related_name="cargas",
                        to="residuos.residuo",
                        verbose_name="Resíduos na Carga",
                    ),
                ),
            ],
        ),
    ]
