# Generated by Django 5.2.7 on 2025-11-25 01:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carga", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carga",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="carga",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="cargaresiduo",
            name="peso_kg",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cargaresiduo",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
